"""remove id field

Revision ID: 0a4065ac37fb
Revises: 38170bec0007
Create Date: 2026-01-11 21:42:30.920686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a4065ac37fb'
down_revision = '38170bec0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('patient_id'))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('patient_id'), ['patient_id'], unique=True)

    # ### end Alembic commands ###
