"""remove facility_id foreign keys

Revision ID: 208c3d0ec3b1
Revises: 0a4065ac37fb
Create Date: 2026-01-12 10:58:50.710790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208c3d0ec3b1'
down_revision = '0a4065ac37fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('1'), type_='foreignkey')

    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('2'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('2'), 'healthcare_facilities', ['facility_id'], ['facility_id'])

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('1'), 'healthcare_facilities', ['facility_id'], ['facility_id'])

    # ### end Alembic commands ###
