"""creates consent records table and establishes necessary relationships

Revision ID: 3254b98c9937
Revises: 3c4fedf2df82
Create Date: 2026-01-10 22:32:51.565664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3254b98c9937'
down_revision = '3c4fedf2df82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('VIEW', 'EDIT', 'SHARE', name='consenttype'), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.Text(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='status'), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['healthcare_facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent_records')
    # ### end Alembic commands ###
