"""implement new relationships for patient IDs

Revision ID: 38170bec0007
Revises: c93178969e31
Create Date: 2026-01-11 20:52:43.947781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38170bec0007'
down_revision = 'c93178969e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('patient_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['patient_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('patient_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
