"""creates access log model and establishes relationships

Revision ID: 3c4fedf2df82
Revises: f9119e530b6f
Create Date: 2026-01-10 15:45:39.668047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4fedf2df82'
down_revision = 'f9119e530b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'EDIT', 'SHARE', name='eventaction'), nullable=True),
    sa.Column('result', sa.Enum('ALLOWED', 'DENIED'), nullable=True),
    sa.Column('reason', sa.Text(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=12), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('accessed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accessed_by'], ['healthcare_workers.worker_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_logs')
    # ### end Alembic commands ###
