"""creates healthcare facility model and estabishes relationships

Revision ID: 45892d57062e
Revises: 6c9ce281db23
Create Date: 2026-01-10 15:24:04.979119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45892d57062e'
down_revision = '6c9ce281db23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_facilities',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('facility_type', sa.Enum('HOSPITAL', 'CLINIC', 'PHARMACY', name='facilitytype'), nullable=True),
    sa.Column('license_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('facility_id')
    )
    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'healthcare_facilities', ['facility_id'], ['facility_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('facility_id')

    op.drop_table('healthcare_facilities')
    # ### end Alembic commands ###
