"""re-introduces facility id relationships

Revision ID: 53a779702441
Revises: aa343fef8269
Create Date: 2026-01-12 11:00:53.277710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a779702441'
down_revision = 'aa343fef8269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'healthcare_facilities', ['facility_id'], ['facility_id'])

    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'healthcare_facilities', ['facility_id'], ['facility_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
