"""adds emergency contact and address fields to the patient model

Revision ID: 547dd2223c42
Revises: 53a779702441
Create Date: 2026-01-12 14:52:35.096141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547dd2223c42'
down_revision = '53a779702441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('emergency_contact')

    # ### end Alembic commands ###
