"""creates healthcare worker model

Revision ID: 6c9ce281db23
Revises: aa43e91c1116
Create Date: 2026-01-10 15:08:41.235164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9ce281db23'
down_revision = 'aa43e91c1116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_workers',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healthcare_workers')
    # ### end Alembic commands ###
