"""adds unique constraints

Revision ID: 95aaaf419a90
Revises: ffc549cbf704
Create Date: 2026-01-11 14:19:22.641320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95aaaf419a90'
down_revision = 'ffc549cbf704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_facilities', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['license_number'])

    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['license_number'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('healthcare_facilities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
