"""change facility id datatype to strings

Revision ID: aa343fef8269
Revises: 208c3d0ec3b1
Create Date: 2026-01-12 10:59:45.721530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa343fef8269'
down_revision = '208c3d0ec3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('healthcare_facilities', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healthcare_workers', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('healthcare_facilities', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
