"""change patient ID datatype from integer to string in affected relationships

Revision ID: c93178969e31
Revises: deda020e2fc6
Create Date: 2026-01-11 19:28:44.310318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93178969e31'
down_revision = 'deda020e2fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
