"""change patient ID datatype from integer to string

Revision ID: deda020e2fc6
Revises: 95aaaf419a90
Create Date: 2026-01-11 19:27:55.913905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deda020e2fc6'
down_revision = '95aaaf419a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('2'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('3'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('3'), 'patients', ['patient_id'], ['patient_id'])

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('2'), 'patients', ['patient_id'], ['patient_id'])

    # ### end Alembic commands ###
