"""increased string length for encrypted national IDs

Revision ID: ffc549cbf704
Revises: 3254b98c9937
Create Date: 2026-01-11 13:50:14.366578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffc549cbf704'
down_revision = '3254b98c9937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('national_id_encrypted',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('national_id_encrypted',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
