"""change email and address from string to text type

Revision ID: 069c24b0035d
Revises: 097b3d02386c
Create Date: 2026-01-12 11:12:13.145997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069c24b0035d'
down_revision = '097b3d02386c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registry_records', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(length=20),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registry_records', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.Text(length=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
