"""adds registry records table

Revision ID: 097b3d02386c
Revises: 
Create Date: 2026-01-10 23:04:44.699699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097b3d02386c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_records',
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=18), nullable=True),
    sa.Column('last_name', sa.String(length=18), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE'), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=60), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registry_records')
    # ### end Alembic commands ###
